force-app/main/default/objects/GoogleCalendar__c/GoogleCalendar__c.object-meta.xml
<CustomObject>
    <label>Google Calendar</label>
    <nameField>
        <label>Google Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Calendars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GoogleCalendar__c/fields/GoogleId__c.field-meta.xml
<CustomField>
    <fullName>GoogleId__c</fullName>
    <label>GoogleId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TL_ConnectMeTests.cls
@isTest
public class TL_ConnectMeTests {
  @testSetup
  static void setup(){
    GoogleCalendar__c calendar = new GoogleCalendar__c(GoogleId__c='calendarId', Default__c=true);
    insert new List<SObject>{ calendar };
  }

  @isTest
  static void connectorController(){
    GenericConnectorController controller = new GenericConnectorController();
    PageReference pr = controller.doGetAuthorizationCode();
    pr = controller.doGetAccessToken();
    controller.doRefreshToken();
  }

  @isTest
  static void calendarActions(){
    TL_CalendarActions.syncCalendars();
  }

  @isTest
  static void apiCall_Test(){
    try {
      TL_GoogleApiCalls.callGoogleApi('endpoint', 'GET', 'null', true);
    } catch (Exception e) {}
  }
}